### ISSUE TITLE
search-functionality

### ISSUE THREAD

**Issue by digitalscribe53** [mancillh/Job-Board#108]

**Comment by joshuamarknanninga** [comment]
i have most of the logic down, it is still throwing an error "hook.js:608 Warning: Image: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. Error Component Stack
    at Image (semantic-ui-react.js?v=85050e47:5423:22)
    at div (<anonymous>)
    at Header (Header.jsx:5:19)
    at App (App.jsx:10:41)
    at RenderedRoute (react-router-dom.js?v=85050e47:4092:5)
    at RenderErrorBoundary (react-router-dom.js?v=85050e47:4052:5)
    at DataRoutes (react-router-dom.js?v=85050e47:5211:5)
    at Router (react-router-dom.js?v=85050e47:4474:15)
    at RouterProvider (react-router-dom.js?v=85050e47:5026:5)
    at ApolloProvider (@apollo_client.js?v=85050e47:6275:19)
overrideMethod @ hook.js:608
Show 1 more frame
Show lessUnderstand this error
:3001/graphql:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)Understand this error
hook.js:608 Error fetching jobs: Array(1)"

this is inside the search-functionality branch!
